### PR TITLE
Allows to import/export plugin settings

### PR DESCRIPTION
**Pull request by abeade**
Allows to import/export plugin settings.
This will help to backup and share messages.

### CODE REVIEW

**Comment by kensiprell** [comment]
Thanks for the PR! This looks like a very good idea. I'll need a few days to get it merged and publish a new release.

**Comment by abeade** [comment]
Thanks to you for the extension! No problem, take the time you need. Also feel free to change whatever you think can be improved, or any text if needed (or just request me the change and I will do it).

**Comment by kensiprell** [comment]
I've made some cosmetic and English changes in addition to opening a saveAs file manager when exporting the file. I wasn't sure where Chrome put it at first, so I opted for this technique to involve the user. 

If you want to take a look, use the `export-import` branch. Feedback is very welcome.

I still have to write some tests for the new features, and I should be finished this weekend.

Thanks again for the PR. It was a great idea!

**Comment by abeade** [comment]
Hi @kensiprell Nice changes!
Maybe you can also update the `README.md` to include the new section documentation, but up to you.

**Comment by kensiprell** [comment]
Thanks! The README is on my to-do list.

**Comment by kensiprell** [comment]
I've decided to quit maintaining this extension. It's too much work, and I no longer enjoy it. Simply updating dependencies always breaks the testing framework among other things, and I spend more time fixing those than implementing features.

If you'd like to maintain it, please let me know. I can transfer the Chrome store ownership to you and put a link in the readme that points to your repo as the current one.

**Pull request merged**
